CREATE DATABASE daoteste;

CREATE TABLE car ( 
 id INT UNSIGNED NOT NULL AUTO_INCREMENT ,
 brand VARCHAR(100) NOT NULL , 
 km INT NOT NULL , 
 color VARCHAR(50) NOT NULL ,
 PRIMARY KEY (`id`)) ENGINE = InnoDB;